### Show all available metrics

GET http://localhost:9000/actuator/metrics
Accept: application/json

### Fetch cart.sessions metric

GET http://localhost:9000/actuator/metrics/cart.sessions
Accept: application/json

### Fetch orders.completed metric

GET http://localhost:9000/actuator/metrics/orders.completed
Accept: application/json

### Fetch service-times metric

GET http://localhost:9000/actuator/metrics/service-times
Accept: application/json

### Fetch service-times for a dedicated use case

GET http://localhost:9000/actuator/metrics/service-times?tag=use-case:<replace-with-use-case-value>
Accept: application/json

### Fetch business metrics via custom Actuator endpoint

GET http://localhost:9000/actuator/businessMetrics
Accept: application/json

### Fetch all active Actuator endpoints

GET http://localhost:9000/actuator
Accept: application/json